apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - pod_disruption_budget.yaml
  - service.yaml
  - service_account.yaml
  - stateful_set.yaml
